CREATE TABLE IF NOT EXISTS payment_order (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    payment_no VARCHAR(64) NOT NULL,
    channel_code VARCHAR(32) NOT NULL,
    channel_trade_no VARCHAR(128) NULL,
    payment_method VARCHAR(32) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    status VARCHAR(32) NOT NULL,
    status_reason VARCHAR(255) NULL,
    requested_at DATETIME NOT NULL,
    paid_at DATETIME NULL,
    closed_at DATETIME NULL,
    last_checked_at DATETIME NULL,
    next_check_at DATETIME NULL,
    check_count INT NOT NULL DEFAULT 0,
    remark VARCHAR(255) NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_payment_order_no (tenant_id, payment_no),
    KEY idx_payment_order_trade (tenant_id, channel_code, channel_trade_no),
    KEY idx_payment_order_status_check (tenant_id, status, next_check_at),
    KEY idx_payment_order_order (tenant_id, order_id, created_at)
);

CREATE TABLE IF NOT EXISTS refund_order (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    refund_no VARCHAR(64) NOT NULL,
    payment_order_id BIGINT NULL,
    channel_code VARCHAR(32) NOT NULL,
    channel_refund_no VARCHAR(128) NULL,
    refund_method VARCHAR(32) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    status VARCHAR(32) NOT NULL,
    status_reason VARCHAR(255) NULL,
    requested_at DATETIME NOT NULL,
    refunded_at DATETIME NULL,
    closed_at DATETIME NULL,
    last_checked_at DATETIME NULL,
    next_check_at DATETIME NULL,
    check_count INT NOT NULL DEFAULT 0,
    remark VARCHAR(255) NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_refund_order_no (tenant_id, refund_no),
    KEY idx_refund_order_channel_no (tenant_id, channel_code, channel_refund_no),
    KEY idx_refund_order_status_check (tenant_id, status, next_check_at),
    KEY idx_refund_order_order (tenant_id, order_id, created_at)
);
